---

version: "2"

checks:
  method-complexity:
    config:
      threshold: 6

  similar-code:
    enabled: false

plugins:
  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Don't leave trailing whitespace"
          severity: minor
          categories: Style
          path_patterns:
            - .rubocop.yml
            - .travis.yml

        no-tabs:
          pattern: "	"
          annotation: "Don't use hard tabs"
          severity: minor
          categories: Style
          path_patterns:
            - .rubocop.yml
            - .travis.yml

exclude_patterns:
  - .bundle/
