# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: "../.."

group :development do
  gem "rake", "~> 13.0"

  gem "chandler", "0.9.0"
  gem "mdl", "0.9.0"
  gem "minitest", "~> 5.14"
  gem "minitest-bisect", "~> 1.5"
  gem "pry", git: "https://github.com/pry/pry.git"
  gem "rubocop", "0.80.0"
  gem "simplecov", "0.17.1"
end
